---
name: we_3.0
beta: 3.0
nbins: 100
target_count: 50
tau: 10
propagator_block_size: 5001
adjust_counts: True
protocols:
    - name: phase1
      max_iterations: 800
      wess: {do_reweighting: True, window_size: 0.5, reweight_period: 20, max_window_size: 2000}
      stringmethod: {do_update: True, windowsize: 50, update_interval: 10, initial_update: 10}
    - name: phase2
      max_iterations: 5000
      wess: {do_reweighting: True, window_size: 0.5, reweight_period: 20, max_window_size: 2000}
      stringmethod: {do_update: False, windowsize: 50, update_interval: 10, initial_update: 10}
    - name: phase3
      max_iterations: 25000
      wess: {do_reweighting: False, window_size: 0.5, reweight_period: 20, max_window_size: 2000}
      stringmethod: {do_update: False, windowsize: 50, update_interval: 10, initial_update: 10}
analysis:
    winsize_flux: 200
    winsize_err: 5
    last_n: 300
    bf_dt: 20.0
    bf_blocksize: 500000
    directions: [0,1]

